name: Daily Quote Update
on:
  schedule:
    - cron: "0 0 * * *"

env:
  TIME_ZONE: "Asia/Kathmandu"

jobs:
  update_quote:
    runs-on: ubuntu-latest
    steps:
      - name: Set up time zone
        run: |
          sudo ln -sf /usr/share/zoneinfo/$TIME_ZONE /etc/localtime
          echo $TIME_ZONE | sudo tee /etc/timezone
          date

      - name: Check out repository
        uses: actions/checkout@v2

      - name: Run script
        run: |
          chmod +x quote.sh
          ./quote.sh

      - name: Commit and push changes
        run: |
          git config --local user.email "stutiupreti12@gmail.com"
          git config --local user.name "thestuti"
          git add README.md
          git commit -m "Update quote"
          git push origin main
